### PR TITLE
[PTAL] update

### PR DESCRIPTION
**Pull request by lawvs**
- [x] fix 404 page return HTTP 200
- [x] refactor router to separate file
- [x] add test
- [x] travis ci supports
- [ ] add customize headers supports (Reverted)

### CODE REVIEW

**Comment by lawvs** [comment]
whether options and headers needs to reverse,because of there are partial duplication with cors.

**Comment by MZIchenjl** [comment]
i don't think the headers is necessary in this case

**Comment by lawvs** [comment]
maybe some RESTful app need customized headers information in response.
for example  [GitHub REST API v3 #request-specific-version](https://developer.github.com/v3/media/#request-specific-version)

```bash
$ curl https://api.github.com/users/technoweenie -I
HTTP/1.1 200 OK
X-GitHub-Media-Type: github.v3

$ curl https://api.github.com/users/technoweenie -I \
 -H "Accept: application/vnd.github.full+json"
HTTP/1.1 200 OK
X-GitHub-Media-Type: github.v3; param=full; format=json

$ curl https://api.github.com/users/technoweenie -I \
 -H "Accept: application/vnd.github.v3.full+json"
HTTP/1.1 200 OK
X-GitHub-Media-Type: github.v3; param=full; format=json
```

**Comment by MZIchenjl** [comment]
Without these information, a web app couldn't be affected. The mockjs focuses on generating data for testing, not simulating a web server.

**Comment by lawvs** [comment]
OK. so I just add a test. By the way, merge is recommended to use squash parameter.

**Pull request merged**
